UserBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 55
            fixed: false
    lifecycleCallbacks: {  }
