UserBundle\Entity\Usergroup:
    type: entity
    table: usergroup
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        groupId:
            type: integer
            nullable: true
            unsigned: false
            column: group_id
        userId:
            type: integer
            nullable: true
            unsigned: false
            column: user_id
    lifecycleCallbacks: {  }
